name: py312
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libavif_api=1.3.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aiosignal=1.4.0
  - aom=3.9.1
  - arrow-cpp=19.0.0
  - async-timeout=5.0.1
  - attrs=25.3.0
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlicffi=1.0.9.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.8.3
  - cairo=1.18.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - contourpy=1.3.3
  - cuda-cccl=12.9.27
  - cuda-cccl_win-64=12.9.27
  - cuda-cudart=12.4.127
  - cuda-cudart-dev=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-libraries-dev=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvrtc-dev=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.9.19
  - cuda-opencl-dev=12.9.19
  - cuda-profiler-api=12.9.79
  - cuda-runtime=12.4.1
  - cuda-version=12.9
  - cycler=0.12.1
  - datasets=4.0.0
  - dav1d=1.2.1
  - dill=0.3.8
  - eigen=3.4.0
  - expat=2.7.1
  - filelock=3.17.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.2
  - freeglut=3.4.0
  - freetype=2.13.3
  - fribidi=1.0.10
  - frozenlist=1.7.0
  - fsspec=2025.3.0
  - gflags=2.2.2
  - giflib=5.2.2
  - glog=0.5.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - gst-plugins-base=1.24.12
  - gstreamer=1.24.12
  - gstreamer-orc=0.4.41
  - harfbuzz=10.2.0
  - hdf5=1.14.5
  - hf-xet=1.1.8
  - huggingface_hub=0.34.4
  - icc_rt=2022.1.0
  - icu=73.2
  - idna=3.7
  - intel-openmp=2023.1.0
  - jinja2=3.1.6
  - jpeg=9e
  - khronos-opencl-icd-loader=2024.05.08
  - kiwisolver=1.4.9
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20250127.0
  - libavif=1.3.0
  - libavif16=1.3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcublas=12.4.5.8
  - libcublas-dev=12.4.5.8
  - libcufft=11.2.1.3
  - libcufft-dev=11.2.1.3
  - libcurand=10.3.10.19
  - libcurand-dev=10.3.10.19
  - libcurl=8.15.0
  - libcusolver=11.6.1.9
  - libcusolver-dev=11.6.1.9
  - libcusparse=12.3.1.170
  - libcusparse-dev=12.3.1.170
  - libdeflate=1.22
  - libexpat=2.7.1
  - libffi=3.4.4
  - libglib=2.84.2
  - libgrpc=1.71.0
  - libiconv=1.18
  - libjpeg-turbo=2.0.0
  - libkrb5=1.21.3
  - libnpp=12.2.5.30
  - libnpp-dev=12.2.5.30
  - libnvfatbin=12.9.82
  - libnvfatbin-dev=12.9.82
  - libnvjitlink=12.4.127
  - libnvjitlink-dev=12.4.127
  - libnvjpeg=12.3.1.117
  - libnvjpeg-dev=12.3.1.117
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libthrift=0.15.0
  - libtiff=4.7.0
  - libuv=1.48.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib-base=3.10.1
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - multidict=6.6.3
  - multiprocess=0.70.15
  - munkres=1.1.4
  - networkx=3.5
  - numexpr=2.11.0
  - numpy=2.0.1
  - numpy-base=2.0.1
  - opencv=4.10.0
  - openjpeg=2.5.2
  - openssl=3.5.2
  - orc=2.1.1
  - packaging=25.0
  - pandas=2.3.2
  - pcre2=10.42
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - propcache=0.3.1
  - pyarrow=19.0.0
  - pycocotools=2.0.10
  - pycparser=2.21
  - pyparsing=3.2.3
  - pysocks=1.7.1
  - python=3.12.3
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.1
  - python-tzdata=2025.2
  - python-xxhash=3.5.0
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-cuda=12.4
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - qhull=2020.2
  - qtbase=6.7.3
  - rav1e=0.7.1
  - re2=2024.07.02
  - regex=2025.7.34
  - requests=2.32.5
  - safetensors=0.6.2
  - setuptools=78.1.1
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.50.2
  - svt-av1=3.1.2
  - sympy=1.14.0
  - tbb=2021.8.0
  - timm=1.0.19
  - tk=8.6.15
  - tokenizers=0.22.0
  - tqdm=4.67.1
  - transformers=4.56.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - ucrt=10.0.22621.0
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wheel=0.45.1
  - win_inet_pton=1.1.0
  - xxhash=0.8.0
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.20.1
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - torchaudio==2.5.1
      - torchvision==0.20.1
prefix: C:\Aplikacje\Anaconda\envs\py312
